export const tryAgainError = "Try again! Something went wrong";
